# Generated by Django 5.0.6 on 2024-07-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GGA',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(default='', max_length=100)),
                ('longitute', models.CharField(default='', max_length=100)),
                ('num_sats', models.CharField(default='', max_length=100)),
                ('altitude', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GSA',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('pdop', models.CharField(default='', max_length=100)),
                ('hdop', models.CharField(default='', max_length=100)),
                ('vdop', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
