# Generated by Django 5.0.6 on 2024-07-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSV',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('elevation_deg_1', models.CharField(default='', max_length=100)),
                ('elevation_deg_2', models.CharField(default='', max_length=100)),
                ('elevation_deg_3', models.CharField(default='', max_length=100)),
                ('elevation_deg_4', models.CharField(default='', max_length=100)),
                ('azimuth_1', models.CharField(default='', max_length=100)),
                ('azimuth_2', models.CharField(default='', max_length=100)),
                ('azimuth_3', models.CharField(default='', max_length=100)),
                ('azimuth_4', models.CharField(default='', max_length=100)),
                ('snr_1', models.CharField(default='', max_length=100)),
                ('snr_2', models.CharField(default='', max_length=100)),
                ('snr_3', models.CharField(default='', max_length=100)),
                ('snr_4', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
