# Generated by Django 5.0.6 on 2024-07-30 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnss', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GSV',
            new_name='GSVData',
        ),
    ]
