# Generated by Django 5.0.6 on 2024-07-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnss', '0005_rename_gsv_gsvdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GSVData',
        ),
    ]
