# Generated by Django 5.0.6 on 2024-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gnss', '0006_delete_gsvdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSVData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sat_type', models.CharField(default='', max_length=50)),
                ('sv_prn_num_1', models.IntegerField(default='', max_length=100)),
                ('sv_prn_num_2', models.IntegerField(default='', max_length=100)),
                ('sv_prn_num_3', models.IntegerField(default='', max_length=100)),
                ('sv_prn_num_4', models.IntegerField(default='', max_length=100)),
                ('elevation_deg_1', models.IntegerField(default='', max_length=100)),
                ('elevation_deg_2', models.IntegerField(default='', max_length=100)),
                ('elevation_deg_3', models.IntegerField(default='', max_length=100)),
                ('elevation_deg_4', models.IntegerField(default='', max_length=100)),
                ('azimuth_1', models.IntegerField(default='', max_length=100)),
                ('azimuth_2', models.IntegerField(default='', max_length=100)),
                ('azimuth_3', models.IntegerField(default='', max_length=100)),
                ('azimuth_4', models.IntegerField(default='', max_length=100)),
                ('snr_1', models.IntegerField(default='', max_length=100)),
                ('snr_2', models.IntegerField(default='', max_length=100)),
                ('snr_3', models.IntegerField(default='', max_length=100)),
                ('snr_4', models.IntegerField(default='', max_length=100)),
            ],
        ),
    ]
