# Generated by Django 5.0.6 on 2024-08-03 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnss', '0011_biedou_data_galileo_data_glonass_data_gps_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biedou_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='galileo_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='glonass_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gps_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='irnss_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
