from django.db import models
from django.utils.timezone import now

# Create your models here.

class GPS_data(models.Model):
    sno=models.AutoField(primary_key=True)
    sv_prn_num_1=models.IntegerField()
    sv_prn_num_2=models.IntegerField()
    sv_prn_num_3=models.IntegerField()
    sv_prn_num_4=models.IntegerField()
    elevation_deg_1=models.IntegerField()
    elevation_deg_2=models.IntegerField()
    elevation_deg_3=models.IntegerField()
    elevation_deg_4=models.IntegerField()
    azimuth_1=models.IntegerField()
    azimuth_2=models.IntegerField()
    azimuth_3=models.IntegerField()
    azimuth_4=models.IntegerField()
    snr_1=models.IntegerField()
    snr_2=models.IntegerField()
    snr_3=models.IntegerField()
    snr_4=models.IntegerField()
    date=models.DateTimeField(default=now)

class GLONASS_data(models.Model):
    sno=models.AutoField(primary_key=True)
    sv_prn_num_1=models.IntegerField()
    sv_prn_num_2=models.IntegerField()
    sv_prn_num_3=models.IntegerField()
    sv_prn_num_4=models.IntegerField()
    elevation_deg_1=models.IntegerField()
    elevation_deg_2=models.IntegerField()
    elevation_deg_3=models.IntegerField()
    elevation_deg_4=models.IntegerField()
    azimuth_1=models.IntegerField()
    azimuth_2=models.IntegerField()
    azimuth_3=models.IntegerField()
    azimuth_4=models.IntegerField()
    snr_1=models.IntegerField()
    snr_2=models.IntegerField()
    snr_3=models.IntegerField()
    snr_4=models.IntegerField()
    date=models.DateTimeField(default=now)

class GALILEO_data(models.Model):
    sno=models.AutoField(primary_key=True)
    sv_prn_num_1=models.IntegerField()
    sv_prn_num_2=models.IntegerField()
    sv_prn_num_3=models.IntegerField()
    sv_prn_num_4=models.IntegerField()
    elevation_deg_1=models.IntegerField()
    elevation_deg_2=models.IntegerField()
    elevation_deg_3=models.IntegerField()
    elevation_deg_4=models.IntegerField()
    azimuth_1=models.IntegerField()
    azimuth_2=models.IntegerField()
    azimuth_3=models.IntegerField()
    azimuth_4=models.IntegerField()
    snr_1=models.IntegerField()
    snr_2=models.IntegerField()
    snr_3=models.IntegerField()
    snr_4=models.IntegerField()
    date=models.DateTimeField(default=now)

class Biedou_data(models.Model):
    sno=models.AutoField(primary_key=True)
    sv_prn_num_1=models.IntegerField()
    sv_prn_num_2=models.IntegerField()
    sv_prn_num_3=models.IntegerField()
    sv_prn_num_4=models.IntegerField()
    elevation_deg_1=models.IntegerField()
    elevation_deg_2=models.IntegerField()
    elevation_deg_3=models.IntegerField()
    elevation_deg_4=models.IntegerField()
    azimuth_1=models.IntegerField()
    azimuth_2=models.IntegerField()
    azimuth_3=models.IntegerField()
    azimuth_4=models.IntegerField()
    snr_1=models.IntegerField()
    snr_2=models.IntegerField()
    snr_3=models.IntegerField()
    snr_4=models.IntegerField()
    date=models.DateTimeField(default=now)

class IRNSS_data(models.Model):
    sno=models.AutoField(primary_key=True)
    sv_prn_num_1=models.IntegerField()
    sv_prn_num_2=models.IntegerField()
    sv_prn_num_3=models.IntegerField()
    sv_prn_num_4=models.IntegerField()
    elevation_deg_1=models.IntegerField()
    elevation_deg_2=models.IntegerField()
    elevation_deg_3=models.IntegerField()
    elevation_deg_4=models.IntegerField()
    azimuth_1=models.IntegerField()
    azimuth_2=models.IntegerField()
    azimuth_3=models.IntegerField()
    azimuth_4=models.IntegerField()
    snr_1=models.IntegerField()
    snr_2=models.IntegerField()
    snr_3=models.IntegerField()
    snr_4=models.IntegerField()
    date=models.DateTimeField(default=now)